apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: apollo-collaboration-server
  name: apollo-collaboration-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apollo-collaboration-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: apollo-collaboration-server
    spec:
      containers:
        - env:
            - name: ALLOW_GUEST_USER
              value: "true"
            - name: ALLOW_ROOT_USER
              value: "true"
            - name: FILE_UPLOAD_FOLDER
              value: /data/uploads
            - name: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
            - name: JWT_SECRET
            - name: LOG_LEVELS
              value: error,warn,log,debug
            - name: MONGODB_URI
              value: mongodb://mongo-node-1:27017,mongo-node-2:27018/apolloDb?replicaSet=rs0
            - name: ROOT_USER_NAME
            - name: ROOT_USER_PASSWORD
            - name: SESSION_SECRET
            - name: URL
          image: ghcr.io/gmod/apollo-collaboration-server:development
          name: apollo-collaboration-server
          ports:
            - containerPort: 3999
              protocol: TCP
          volumeMounts:
            - mountPath: /data/uploads
              name: uploaded-files-volume
      restartPolicy: Always
      volumes:
        - name: uploaded-files-volume
          persistentVolumeClaim:
            claimName: uploaded-files-volume
