apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: uploaded-files-volume
  name: uploaded-files-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
